### PR TITLE
Login routes added to backend

### PR DESCRIPTION
**Pull request by NipunDas**
Tested and functional signup and login routes added to backend server. Currently usernames/passwords are not stored persistently in the DB and routes are not protected by requiring tokens since the frontend has not been updated to use this login system yet.

### CODE REVIEW

**Comment by NipunDas** [comment]
Note that the workflow fails because Azure only allows 3 staging environments to be running at once and at the time of writing this comment there are 4 pull requests open.

**Comment by lucawperri** [comment]
All of this looks good! It looks like maybe some dependencies were added in the package.json so I think if anything just make sure that if something needs to be installed it's shown on the readme.

**Review by lucawperri — APPROVED** [review]

**Comment by PaytonOAnderson** [comment]
looks good, I will work on updating the frontend to use this system

**Comment by Muhammad8493** [comment]
Nice work on adding backend routes for authentication, would be great to see this fully functioning with the frontend. I agree with Luca on updating the readme to accurately inform of needed dependencies. Additionally, would need to run the Azure checks once one fewer PR is staged.

**Comment by Proefey** [comment]
Nice Job Overall with the code, could use a bit more comments on auth.js to help explain but that's the only criticism I had

**Comment by NipunDas** [comment]
> All of this looks good! It looks like maybe some dependencies were added in the package.json so I think if anything just make sure that if something needs to be installed it's shown on the readme.

Thanks for the suggestion! Yes, new dependencies were added for the auth process. However, I noticed that we have added a lot of dependencies throughout this project and it isn't realistic to list all of them in the README, so I instead added a note to the contributing section of the README, that tells contributors to use the `npm update` command to get all new dependencies/update outdating ones.

**Comment by NipunDas** [comment]
> Nice work on adding backend routes for authentication, would be great to see this fully functioning with the frontend. I agree with Luca on updating the readme to accurately inform of needed dependencies. Additionally, would need to run the Azure checks once one fewer PR is staged.

Thanks for the suggestions! I will make sure to check back on the workflow once fewer PRs are open, and will be integrating the auth routes with the frontend soon.

**Comment by NipunDas** [comment]
> Nice Job Overall with the code, could use a bit more comments on auth.js to help explain but that's the only criticism I had

Thanks for the feedback! I went ahead and added more comments to auth.js, which explain what each function does within the authorization and authentication process.

**Pull request merged**
