### PR TITLE
Organized and Fixed Bugs

### PR DESCRIPTION
**Pull request by Proefey**
Calendar Code Now Correctly Displays Descriptions Of Tasks
All Helper Functions Can Now Be Found On Top Of Module
Added Comments To Increase Clarity
Other Bugs Fixed

### CODE REVIEW

**Comment by PaytonOAnderson** [comment]
Looks like it still works, I don't see any issues, it should be all good to merge

**Review by lucawperri — APPROVED** [review]
Looks good, thank you for the helpful changes!

**Comment by NipunDas** [comment]
The code looks good to me and the deploy version works great! Curious as to what bugs were fixed @Proefey .

**Comment by Muhammad8493** [comment]
Code looks good and nice work on adding to the comments to help create clarity.

**Review by Muhammad8493 — APPROVED** [review]

**Comment by Proefey** [comment]
> The code looks good to me and the deploy version works great! Curious as to what bugs were fixed @Proefey .

Descriptions Were Not Appearing On Weekly/Daily Calendar
Monthly Calendar Was Incorrectly Placing Events Starting From The Second Event Array In Each Square

**Pull request merged**
