### PR TITLE
List frontend dnd

### PR DESCRIPTION
**Pull request by Muhammad8493**
As a user, I want to be able to move around items in the todo list.

### CODE REVIEW

**Comment by lucawperri** [comment]
Looks good, great work!

**Comment by NipunDas** [comment]
I added a few commits to fix the issues that caused the workflow to not work, most of which were either linting errors or something to do with the node version used by the workflow. The code itself looks good to me though and the drag and drop works great!

**Comment by PaytonOAnderson** [comment]
Good work, the moving tasks look great!

**Comment by Muhammad8493** [comment]
Appreciate the feedback and the help with fixing the workflow issues related to linting and node versions. Another thing I fixed in a subsequent PR request was removing unnecessary files and moving others to the correct folders.

**Comment by Proefey** [comment]
The code looks great and I like how the code is very organized, making it easy to read from top to bottom and understand the process.

**Pull request merged**
